import{S as d,i as m}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const g="32445891-4e5aca6c6794ec22921e6fc5b",a=document.querySelector(".form"),c=document.querySelector(".gallery"),p=document.querySelector(".loader");function h(){p.style.display="inline-block"}function l(){p.style.display="none"}const L=new d(".gallery_list a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function _(i){const r=i.hits.reduce((o,{webformatURL:s,largeImageURL:e,tags:t,likes:n,views:u,comments:f,downloads:y})=>o+`
         <li class='gallery_list'>
          <a href="${e}"><img class='gallery_img'src="${s}" alt="${t}" /></a>
          <p class='gallery_info'>Likes <span>${n}</span></p>
          <p class='gallery_info'>Views <span>${u}</span></p>
          <p class='gallery_info'>Comments <span>${f}</span></p>
          <p class='gallery_info'>Downloads <span>${y}</span></p>
        </li>`,"");c.innerHTML=r,L.refresh()}a.addEventListener("submit",i=>{i.preventDefault();const r=a.querySelector(".form_input").value;c.innerHTML="",h(),fetch("https://pixabay.com/api/?key="+g+"&q="+r+"&image_type=photo&orientation=horizontal&safesearch=true&per_page=50").then(o=>{if(!o.ok)throw new Error("Error");return o.json()}).then(o=>{l(),o.total||m.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),_(o)}).catch(o=>{l(),console.log(o)})});
//# sourceMappingURL=commonHelpers.js.map
